{"name": "test_list1", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\n  \n  Right contains one more item: 5\n  \n  Full diff:\n    [\n        1,\n        2,...\n  \n  ...Full output truncated (4 lines hidden), use '-vv' to show", "trace": "self = <test_add.TestAdd object at 0x72ab85aafd10>\n\n    @pytest.mark.xfail  # expected to be failed, and actual failed, xfailed\n    @pytest.mark.api\n    def test_list1(self):\n        res = add([1], [2, 3, 4])\n>       assert res == [1, 2, 3, 4, 5]\nE       AssertionError: assert [1, 2, 3, 4] == [1, 2, 3, 4, 5]\nE         \nE         Right contains one more item: 5\nE         \nE         Full diff:\nE           [\nE               1,\nE               2,...\nE         \nE         ...Full output truncated (4 lines hidden), use '-vv' to show\n\nunit_tests/test_add.py:53: AssertionError"}, "attachments": [{"name": "log", "source": "1397de8e-35d6-4eb5-97ef-0a8d74e4c43a-attachment.txt", "type": "text/plain"}], "start": 1750350693916, "stop": 1750350693916, "uuid": "2634a6c8-d61c-44d4-b70f-7aa70b226582", "historyId": "6f9ec05af584e70b86f4005288e423e7", "testCaseId": "6f9ec05af584e70b86f4005288e423e7", "fullName": "unit_tests.test_add.TestAdd#test_list1", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "unit_tests"}, {"name": "suite", "value": "test_add"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "32592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit_tests.test_add"}]}